---
version: "2.1"
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
      # - MONGO_TLS=
      # - MONGO_AUTHSOURCE=
    volumes:
      - /opt/docker/unifi-controller:/config
    ports:
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp
      - 3478:3478/udp
      - 10001:10001/udp
    networks:
      unifi:
    restart: unless-stopped
  unifi-db:
    image: docker.io/mongo:4.4
    container_name: unifi-db
    volumes:
      - /opt/docker/unifi-controller-db:/data/db
      - /opt/docker-compose/unifi-controller/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      unifi:
    restart: unless-stopped

networks:
  unifi: